server:
  port: 8080

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/exam?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    hikari:
      connect-test-query: SELECT 1
      connection-timeout: 30000
      idle-timeout: 500000
      max-lifetime: 540000
      max-pool-size: 10
      minimum-idle: 10
      pool-name: SPHHikariPool
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 20MB

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

minio:
  endpoint: http://192.168.100.241:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: aiexam